---
 - hosts: host2
   remote_user: vagrant
   become: yes
   become_method: sudo 
   
   tasks:
    - name: copy config file
      copy:
        src: ./snmpd.conf
        dest: /etc/snmp
        owner: vagrant
        group: vagrant
        mode: 0600

    - name: copy config file for forwarding
      copy:
        src: ./rsyslog.conf
        dest: /etc/
        owner: root
        group: root
        mode: 0644
    
    - name: ensure services is running
      service:
       name: snmpd
       state: restarted

    - name: Start syslog
      service:
       name: rsyslog
       state: restarted

    - name: Change permission to be able to write into nagios log
      ansible.builtin.file:
        path: /usr/local/nagios/var/nagios.log
        owner: nagios
        group: nagios
        mode: '0666'
... 
