---
 - hosts: host1
   remote_user: vagrant
   become: yes
   become_method: sudo 
   
   tasks:
    - name: copy config file
      copy:
        src: ./snmpd.conf
        dest: /etc/snmp
        owner: vagrant
        group: vagrant
        mode: 0600
    
    - name: ensure services is running
      service:
       name: snmpd
       state: restarted

    - name: Start syslog
      service:
       name: rsyslog
       state: restarted
... 
